config/routes.rb
Rails.application.routes.draw do
  resources :player_item_stats
  resources :player_items
  resources :fixed_item_stats
  resources :magic_item_names
  resources :common_items
  devise_for :users
  resources :item_rarities
  resources :stat_types
  resources :item_tiers
  resources :roll do
    collection do
      post :generate_drops
    end
  end

  root 'welcome#index'

end

app/models/player_item_stat.rb
class PlayerItemStat < ActiveRecord::Base
  belongs_to :player_item
  belongs_to :stat_type
end

app/controllers/player_item_stats_controller.rb
class PlayerItemStatsController < ApplicationController
  before_action :set_player_item_stat, only: [:show, :edit, :update, :destroy]

  # GET /player_item_stats
  # GET /player_item_stats.json
  def index
    @player_item_stats = PlayerItemStat.all
  end

  # GET /player_item_stats/1
  # GET /player_item_stats/1.json
  def show
  end

  # GET /player_item_stats/new
  def new
    @player_item_stat = PlayerItemStat.new
  end

  # GET /player_item_stats/1/edit
  def edit
  end

  # POST /player_item_stats
  # POST /player_item_stats.json
  def create
    @player_item_stat = PlayerItemStat.new(player_item_stat_params)

    respond_to do |format|
      if @player_item_stat.save
        format.html { redirect_to @player_item_stat, notice: 'Player item stat was successfully created.' }
        format.json { render :show, status: :created, location: @player_item_stat }
      else
        format.html { render :new }
        format.json { render json: @player_item_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_item_stats/1
  # PATCH/PUT /player_item_stats/1.json
  def update
    respond_to do |format|
      if @player_item_stat.update(player_item_stat_params)
        format.html { redirect_to @player_item_stat, notice: 'Player item stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_item_stat }
      else
        format.html { render :edit }
        format.json { render json: @player_item_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_item_stats/1
  # DELETE /player_item_stats/1.json
  def destroy
    @player_item_stat.destroy
    respond_to do |format|
      format.html { redirect_to player_item_stats_url, notice: 'Player item stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_item_stat
      @player_item_stat = PlayerItemStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_item_stat_params
      params.require(:player_item_stat).permit(:stat_type_id, :stat_value, :player_item_id)
    end
end

app/helpers/player_item_stats_helper.rb
module PlayerItemStatsHelper
end

app/views/player_item_stats/_form.html.haml
= form_for @player_item_stat do |f|
  - if @player_item_stat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player_item_stat.errors.count, "error")} prohibited this player_item_stat from being saved:"
      %ul
        - @player_item_stat.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :stat_type
    = f.text_field :stat_type
  .field
    = f.label :stat_value
    = f.number_field :stat_value
  .field
    = f.label :player_item
    = f.text_field :player_item
  .actions
    = f.submit 'Save'

app/views/player_item_stats/edit.html.haml
%h1 Editing player_item_stat

= render 'form'

= link_to 'Show', @player_item_stat
\|
= link_to 'Back', player_item_stats_path

app/views/player_item_stats/index.html.haml
%h1 Listing player_item_stats

%table
  %thead
    %tr
      %th Stat type
      %th Stat value
      %th Player item
      %th
      %th
      %th

  %tbody
    - @player_item_stats.each do |player_item_stat|
      %tr
        %td= player_item_stat.stat_type
        %td= player_item_stat.stat_value
        %td= player_item_stat.player_item
        %td= link_to 'Show', player_item_stat
        %td= link_to 'Edit', edit_player_item_stat_path(player_item_stat)
        %td= link_to 'Destroy', player_item_stat, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Player item stat', new_player_item_stat_path

app/views/player_item_stats/new.html.haml
%h1 New player_item_stat

= render 'form'

= link_to 'Back', player_item_stats_path

app/views/player_item_stats/show.html.haml
%p#notice= notice

%p
  %b Stat type:
  = @player_item_stat.stat_type
%p
  %b Stat value:
  = @player_item_stat.stat_value
%p
  %b Player item:
  = @player_item_stat.player_item

= link_to 'Edit', edit_player_item_stat_path(@player_item_stat)
\|
= link_to 'Back', player_item_stats_path