config/routes.rb
Rails.application.routes.draw do
  resources :player_item_stats
  resources :player_items
  resources :fixed_item_stats
  resources :magic_item_names
  resources :common_items
  devise_for :users
  resources :item_rarities
  resources :stat_types
  resources :item_tiers
  resources :roll do
    collection do
      post :generate_drops
    end
  end

  root 'welcome#index'

end

app/models/player_item.rb
class PlayerItem < ActiveRecord::Base
  belongs_to :item_rarity
  belongs_to :user
  belongs_to :stat_type
  belongs_to :item_slot
  has_many :player_item_stats
  attr_accessor :monster_level
  attr_accessor :monster_difficulty
end

app/controllers/player_items_controller.rb
class PlayerItemsController < ApplicationController
  before_action :set_player_item, only: [:show, :edit, :update, :destroy]

  # GET /player_items
  # GET /player_items.json
  def index
    @player_items = PlayerItem.all
  end

  # GET /player_items/1
  # GET /player_items/1.json
  def show
  end

  # GET /player_items/new
  def new
    @player_item = PlayerItem.new
  end

  # GET /player_items/1/edit
  def edit
  end

  # POST /player_items
  # POST /player_items.json
  def create
    monster_level = player_item_params['monster_level'].to_i
    monster_difficulty = player_item_params['monster_difficulty'].to_i
    @base_drops = roll_base_drops(monster_level, monster_difficulty)

    @player_item = PlayerItem.new(player_item_params)

    respond_to do |format|
      if @base_drops
        format.html { redirect_to @player_item, notice: "Items Generated" }
        format.json { render :show, status: :created, location: @player_item }
      else
        format.html { render :new }
        format.json { render json: @player_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_items/1
  # PATCH/PUT /player_items/1.json
  def update
    respond_to do |format|
      if @player_item.update(player_item_params)
        format.html { redirect_to @player_item, notice: 'Player item was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_item }
      else
        format.html { render :edit }
        format.json { render json: @player_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_items/1
  # DELETE /player_items/1.json
  def destroy
    @player_item.destroy
    respond_to do |format|
      format.html { redirect_to player_items_url, notice: 'Player item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_item
      @player_item = PlayerItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_item_params
      params.require(:player_item).permit(:full_name, :item_rarity_id, :user_id, :item_tier, :monster_level, :monster_difficulty)
    end
end

app/helpers/player_items_helper.rb
module PlayerItemsHelper
end

app/views/player_items/_form.html.haml
= form_for @player_item do |f|
  - if @player_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player_item.errors.count, "error")} prohibited this player_item from being saved:"
      %ul
        - @player_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :monster_level
    = f.text_field :monster_level
  .field
    = f.label :monster_difficulty
    = f.text_field :monster_difficulty
  .actions
    = f.submit 'Save'

app/views/player_items/edit.html.haml
%h1 Editing player_item

= render 'form'

= link_to 'Show', @player_item
\|
= link_to 'Back', player_items_path

app/views/player_items/index.html.haml
%h1 Listing player_items

%table
  %thead
    %tr
      %th Full name
      %th Item rarity
      %th User
      %th
      %th
      %th

  %tbody
    - @player_items.each do |player_item|
      %tr
        %td= player_item.full_name
        %td= player_item.item_rarity
        %td= player_item.user
        %td= link_to 'Show', player_item
        %td= link_to 'Edit', edit_player_item_path(player_item)
        %td= link_to 'Destroy', player_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br


= link_to 'New Player item', new_player_item_path

app/views/player_items/new.html.haml
%h1 New player_item

= form_for @player_item do |f|
  - if @player_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player_item.errors.count, "error")} prohibited this player_item from being saved:"
      %ul
        - @player_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "monster level (item tier)"
    = f.text_field 'monster_level'
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Generate'


= link_to 'Back', player_items_path

app/views/player_items/show.html.haml
%p#notice= notice

%p
  %b Full name:
  = @player_item.full_name
%p
  %b Item rarity:
  = @player_item.item_rarity
%p
  %b User:
  = @player_item.user

= link_to 'Edit', edit_player_item_path(@player_item)
\|
= link_to 'Back', player_items_path