config/routes.rb
Rails.application.routes.draw do
  resources :player_item_stats
  resources :player_items
  resources :fixed_item_stats
  resources :magic_item_names
  resources :common_items
  devise_for :users
  resources :item_rarities
  resources :stat_types
  resources :item_tiers
  resources :roll do
    collection do
      post :generate_drops
    end
  end

  root 'welcome#index'

end

app/models/item_rarity.rb
class ItemRarity < ActiveRecord::Base
end

app/controllers/item_rarities_controller.rb
class ItemRaritiesController < ApplicationController
  before_action :set_item_rarity, only: [:show, :edit, :update, :destroy]

  # GET /item_rarities
  # GET /item_rarities.json
  def index
    @item_rarities = ItemRarity.all
  end

  # GET /item_rarities/1
  # GET /item_rarities/1.json
  def show
  end

  # GET /item_rarities/new
  def new
    @item_rarity = ItemRarity.new
  end

  # GET /item_rarities/1/edit
  def edit
  end

  # POST /item_rarities
  # POST /item_rarities.json
  def create
    @item_rarity = ItemRarity.new(item_rarity_params)

    respond_to do |format|
      if @item_rarity.save
        format.html { redirect_to @item_rarity, notice: 'Item rarity was successfully created.' }
        format.json { render :show, status: :created, location: @item_rarity }
      else
        format.html { render :new }
        format.json { render json: @item_rarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_rarities/1
  # PATCH/PUT /item_rarities/1.json
  def update
    respond_to do |format|
      if @item_rarity.update(item_rarity_params)
        format.html { redirect_to @item_rarity, notice: 'Item rarity was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_rarity }
      else
        format.html { render :edit }
        format.json { render json: @item_rarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_rarities/1
  # DELETE /item_rarities/1.json
  def destroy
    @item_rarity.destroy
    respond_to do |format|
      format.html { redirect_to item_rarities_url, notice: 'Item rarity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_rarity
      @item_rarity = ItemRarity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_rarity_params
      params.require(:item_rarity).permit(:name)
    end
end

app/helpers/item_rarities_helper.rb
module ItemRaritiesHelper
end

app/views/item_rarities/_form.html.haml
= form_for @item_rarity do |f|
  - if @item_rarity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item_rarity.errors.count, "error")} prohibited this item_rarity from being saved:"
      %ul
        - @item_rarity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/item_rarities/edit.html.haml
%h1 Editing item_rarity

= render 'form'

= link_to 'Show', @item_rarity
\|
= link_to 'Back', item_rarities_path

app/views/item_rarities/index.html.haml
%h1 Listing item_rarities

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @item_rarities.each do |item_rarity|
      %tr
        %td= item_rarity.name
        %td= link_to 'Show', item_rarity
        %td= link_to 'Edit', edit_item_rarity_path(item_rarity)
        %td= link_to 'Destroy', item_rarity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item rarity', new_item_rarity_path

app/views/item_rarities/new.html.haml
%h1 New item_rarity

= render 'form'

= link_to 'Back', item_rarities_path

app/views/item_rarities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item_rarity.name

= link_to 'Edit', edit_item_rarity_path(@item_rarity)
\|
= link_to 'Back', item_rarities_path