config/routes.rb
Rails.application.routes.draw do
  resources :player_item_stats
  resources :player_items
  resources :fixed_item_stats
  resources :magic_item_names
  resources :common_items
  devise_for :users
  resources :item_rarities
  resources :stat_types
  resources :item_tiers
  resources :roll do
    collection do
      post :generate_drops
    end
  end

  root 'welcome#index'

end

app/models/common_item.rb
class CommonItem < ActiveRecord::Base
  belongs_to :item_tier
  belongs_to :stat_type
  belongs_to :item_slot
end

app/models/fixed_item_stat.rb
class FixedItemStat < ActiveRecord::Base
  belongs_to :magic_item_name
  belongs_to :stat_type
end

app/models/item_rarity.rb
class ItemRarity < ActiveRecord::Base
end

app/models/item_slot.rb
class ItemSlot < ActiveRecord::Base
end

app/models/item_tier.rb
class ItemTier < ActiveRecord::Base
end

app/models/magic_item_name.rb
class MagicItemName < ActiveRecord::Base
  belongs_to :item_rarity
  belongs_to :item_tier
  scope :approved_magic_names, ->(act, rarity, affix) { where(item_tier:ItemTier.where(name:act),
                                                       affix:affix,
                                                       item_rarity:ItemRarity.where(name:rarity)) }

end

app/models/player_item.rb
class PlayerItem < ActiveRecord::Base
  belongs_to :item_rarity
  belongs_to :user
  belongs_to :stat_type
  belongs_to :item_slot
  has_many :player_item_stats
  attr_accessor :monster_level
  attr_accessor :monster_difficulty
end

app/models/player_item_stat.rb
class PlayerItemStat < ActiveRecord::Base
  belongs_to :player_item
  belongs_to :stat_type
end

app/models/stat_type.rb
class StatType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/roll_controller.rb
class RollController < ApplicationController
  def generate_drops
    ml = params['monster_level'].to_i
    md = params['monster_difficulty'].to_i
    mf = params['magic_find'].to_i
    @generated_items = roll_base_drops(ml, md, mf, 0)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @player_item = PlayerItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def roll_base_drops(ml, md, mf, drop_num=0)
    if drop_num == 0
      drop_num = get_number_of_base_drops(md)
    end
    # make items based on fixed list
    common_drops = generate_common_items(drop_num,ml)
    # turn white items into actual items
    items = generate_items(common_drops, ml, md)
    # change to magic/rare/unique
    converted_items = Array.new
    items.each do |item|
      if get_unique?(mf)
        converted_items.push convert_to_unique(item)
      elsif get_rare?(mf)
        converted_items.push convert_to_rare(item)
      elsif get_magic?(mf)
        converted_items.push convert_to_magic(item)
      else
        item.player_item_stats = Array.new
        converted_items.push item
      end
    end
    converted_items
  end

  def get_number_of_base_drops(md)
    drop_num = 0
    if percent_chance(2*md*2)
      drop_num = 3
    elsif percent_chance(5*md*2)
      drop_num = 2
    elsif percent_chance(10*md*2)
      drop_num = 1
    end

    if md >= 3
      drop_num += 3
    elsif md == 2
      drop_num += rand(1..2)
    end

    drop_num
  end

  def percent_chance(chance)
    chance = rand(0..90) if chance > 90
    random = rand(0..100)
    random.between?(0,chance)
  end

  def generate_common_items(drop_num,ml)
    i = 0
    items = Array.new
    item_tier = 1
    while i < drop_num do
      if percent_chance(10)
        item_tier = 2
      end
      offset = rand((CommonItem.where(item_tier:item_tier)).count)
      items.push(CommonItem.where(item_tier:item_tier).offset(offset).first)
      i += 1
    end
    items
  end

  def generate_items(drops, ml, md)
    generated_items = Array.new
    drops.each do |drop|
      # white item for now
      player_item = PlayerItem.new(full_name:drop.name,
                                   stat_value:rand(drop.min..drop.max),
                                   stat_type:drop.stat_type,
                                   item_slot:drop.item_slot)
      generated_items.push player_item
    end
    generated_items
  end

  def get_unique?(mf)
    adjusted_mf = 1 + (mf*(0.01))
    percent_chance(1*adjusted_mf)
    false # temporary return false
  end

  def get_rare?(mf)
    adjusted_mf = 1 + (mf*(0.01))
    percent_chance(3*adjusted_mf)
    false # temporary return false
  end

  def get_magic?(mf)
    adjusted_mf = 1 + (mf*(0.01))
    percent_chance(10*adjusted_mf)
  end

  def convert_to_rare(item)
    item
  end

  def convert_to_unique(item)
    item
  end

  def convert_to_magic(item)
    #  prefix/suffix?
    random = rand(1..5)
    magic_item_names = Array.new
    if random == (1 || 2)
      # affix
      magic_item_names.push get_random_affix
    elsif random == (3 || 4)
      # suffix
      magic_item_names.push get_random_suffix
    else
      # both
      magic_item_names.push get_random_affix
      magic_item_names.push get_random_suffix
    end
    item.item_rarity = ItemRarity.where(name:"magic").first
    magical_stats = Array.new
    magic_item_names.each do |magic_item_name|
      magic_stats = FixedItemStat.where(magic_item_name:magic_item_name)
      magic_stats.each do |magic_stat|
        stat_value = rand(magic_stat.min..magic_stat.max)
        magical_stats.push PlayerItemStat.new(player_item:item,stat_value:stat_value,stat_type:magic_stat.stat_type)
      end
      if magic_item_name.affix
        item.full_name = magic_item_name.name + " " + item.full_name
      else
        item.full_name = item.full_name + " " + magic_item_name.name
      end
    end
    item.player_item_stats = magical_stats
    item.item_rarity = ItemRarity.where(name:"magic").first
    item
  end

  def get_random_affix()
    offset = rand((MagicItemName.approved_magic_names("act1", "magic", true)).count)
    MagicItemName.approved_magic_names("act1", "magic", true).offset(offset).first
  end

  def get_random_suffix()
    offset = rand((MagicItemName.approved_magic_names("act1", "magic", false)).count)
    MagicItemName.approved_magic_names("act1", "magic", false).offset(offset).first
  end

end

app/helpers/common_items_helper.rb
module CommonItemsHelper
end

app/helpers/fixed_item_stats_helper.rb
module FixedItemStatsHelper
end

app/helpers/item_rarities_helper.rb
module ItemRaritiesHelper
end

app/helpers/item_tiers_helper.rb
module ItemTiersHelper
end

app/helpers/player_items_helper.rb
module PlayerItemsHelper
end

app/helpers/stat_types_helper.rb
module StatTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{role:'navigation'}
  .container
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .small-only
          = link_to root_path, class: 'navbar-brand' do
            .brand-text-small
              .brand-text-small-image
              .brand-text-small-text
                Item Game
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Create New Item
              %span.caret
            %ul.dropdown-menu
              %li
                =link_to "common item", common_items_path
              %li
                =link_to "fixed item stat", fixed_item_stats_path
              %li
                =link_to "item rarity", item_rarities_path
              %li
                =link_to "item tier", item_tiers_path
              %li
                =link_to "magic item name", magic_item_names_path
              %li
                =link_to "stat type", stat_types_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Itemgen
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %header
        =render 'layouts/nav'
      %span.notice
        = notice
      %span.alert
        = alert
      - if user_signed_in?
        %li
          = current_user.email
        %li
          = link_to('Logout', destroy_user_session_path, :method => :delete)
      - else
        %li
          = link_to('Login', new_user_session_path)
      = yield

app/views/partials/_drops_list.html.haml
%ul
  -@generated_items.each do |item|
    %li
      =item.full_name
      ="|"
      ="#{item.stat_value} #{item.stat_type.name}"
      ="|"
      =item.item_slot.name
      %ul
        -unless item.player_item_stats.empty?
          -item.player_item_stats.each do |stat|
            %li
              ="Stat Value: + #{stat.stat_value} #{stat.stat_type.name}"